version: '3.8'

services:
  redis:
    image: redis:8.0-alpine
    container_name: redis-for-apple-web
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data: