spring:
  application:
    name: apple-shop
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: validate
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      database: ${REDIS_DATABASE}
      timeout: 6000
  mail:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: ${JWT_EXPIRATION}
      refresh-token:
        expiration: ${JWT_REFRESH_EXPIRATION}

server:
  servlet:
    context-path: /api/v1
  port: 8080

otp:
  expired.in: 5
  length: 6

google:
  client-id: ${GOOGLE_CLIENT_ID}

vnpay:
  url: ${VNPAY_URL}
  tmnCode: ${VNPAY_TMN_CODE}
  secretKey: ${VNPAY_SECRET_KEY}
  version: ${VNPAY_VERSION}
  command: ${VNPAY_COMMAND}
  orderType: ${VNPAY_ORDER_TYPE}
  returnUrl: ${VNPAY_RETURN_URL}
  ipnUrl: ${VNPAY_IPN_URL}

ghn:
  api:
    url: ${GHN_API_URL}
    token: ${GHN_TOKEN}
    client_id: ${GHN_CLIENT_ID}
    shop_id: ${GHN_SHOP_ID}
