spring:
  application:
    name: apple-shop

  datasource:
    url: jdbc:sqlserver://dqhieuse.database.windows.net:1433;database=apple_shop_dev;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: dqhieuse@dqhieuse
    password: Hieu26102005
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update